### ISSUE TITLE
Ticking entity issue with villagers. (in a server)

### ISSUE THREAD

**Issue by rakostep** [Pannoniae/sodium-forge#24]
Hi I'd like to notify an issue regarding a ticking entity problem involving Sodium. Before I go further, I did check if it's sodium causing it by removing it from the server modlist and launching the server again, which resulted it to not crash.

Here's the description from the crash log:

```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2/19/21 9:01 AM
Description: Ticking entity

java.lang.IllegalArgumentException: Entity listener not tracked:me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityListenerMulti@46b2e2e5 with sublisteners: [me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityTracker@6e35ea66 for entity class: net.minecraft.entity.passive.PolarBearEntity, in rangeSq: 36.0, around entity: VillagerEntity['Villager'/226, l='ServerLevel[world]', x=-216.50, y=64.00, z=-2511.88] with NBT: {Brain:{memories:{"minecraft:meeting_point":{value:{pos:[I;-218,64,-2550],dimension:"minecraft:overworld"}},"minecraft:home":{value:{pos:[I;-220,66,-2486],dimension:"minecraft:overworld"}}}},HurtByTimestamp:0,ForgeData:{},Attributes:[{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.5d,Name:"minecraft:generic.movement_speed"},{Base:48.0d,Modifiers:[{Amount:0.06616450924538962d,Operation:1,UUID:[I;1768818561,818696156,-2019773697,-1463815723],Name:"Random spawn bonus"}],Name:"minecraft:generic.follow_range"}],FoodLevel:0b,Invulnerable:0b,FallFlying:0b,ForcedAge:0,Gossips:[],PortalCooldown:0,AbsorptionAmount:0.0f,LastRestock:0L,FallDistance:0.0f,CanUpdate:1b,DeathTime:0s,Xp:0,LastGossipDecay:10051081L,HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,UUID:[I;-419266458,1089883251,-1176043008,1186277360],Age:0,Motion:[2.3489080142694366E-5d,-0.0784000015258789d,0.13487918769177593d],Health:20.0f,LeftHanded:0b,Air:300s,OnGround:1b,Rotation:[359.97888f,0.0f],HandItems:[{},{}],RestocksToday:0,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Pos:[-216.50016719842122d,64.0d,-2511.8820199442885d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:1b,VillagerData:{profession:"minecraft:none",level:1,type:"minecraft:savanna"},HurtTime:0s,Inventory:[]},me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityTracker@565dbde0 for entity class: net.minecraft.entity.monster.WitchEntity, in rangeSq: 36.0, around entity: VillagerEntity['Villager'/226, l='ServerLevel[world]', x=-216.50, y=64.00, z=-2511.88] with NBT: {Brain:{memories:{"minecraft:meeting_point":{value:{pos:[I;-218,64,-2550],dimension:"minecraft:overworld"}},"minecraft:home":{value:{pos:[I;-220,66,-2486],dimension:"minecraft:overworld"}}}},HurtByTimestamp:0,ForgeData:{},Attributes:[{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.5d,Name:"minecraft:generic.movement_speed"},{Base:48.0d,Modifiers:[{Amount:0.06616450924538962d,Operation:1,UUID:[I;1768818561,818696156,-2019773697,-1463815723],Name:"Random spawn bonus"}],Name:"minecraft:generic.follow_range"}],FoodLevel:0b,Invulnerable:0b,FallFlying:0b,ForcedAge:0,Gossips:[],PortalCooldown:0,AbsorptionAmount:0.0f,LastRestock:0L,FallDistance:0.0f,CanUpdate:1b,DeathTime:0s,Xp:0,LastGossipDecay:10051081L,HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,UUID:[I;-419266458,1089883251,-1176043008,1186277360],Age:0,Motion:[2.3489080142694366E-5d,-0.0784000015258789d,0.13487918769177593d],Health:20.0f,LeftHanded:0b,Air:300s,OnGround:1b,Rotation:[359.97888f,0.0f],HandItems:[{},{}],RestocksToday:0,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Pos:[-216.50016719842122d,64.0d,-2511.8820199442885d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:1b,VillagerData:{profession:"minecraft:none",level:1,type:"minecraft:savanna"},HurtTime:0s,Inventory:[]},me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityTracker@7b41ca03 for entity class: erx.kemonocraft.k7_4835, in rangeSq: 144.0, around entity: VillagerEntity['Villager'/226, l='ServerLevel[world]', x=-216.50, y=64.00, z=-2511.88] with NBT: {Brain:{memories:{"minecraft:meeting_point":{value:{pos:[I;-218,64,-2550],dimension:"minecraft:overworld"}},"minecraft:home":{value:{pos:[I;-220,66,-2486],dimension:"minecraft:overworld"}}}},HurtByTimestamp:0,ForgeData:{},Attributes:[{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.5d,Name:"minecraft:generic.movement_speed"},{Base:48.0d,Modifiers:[{Amount:0.06616450924538962d,Operation:1,UUID:[I;1768818561,818696156,-2019773697,-1463815723],Name:"Random spawn bonus"}],Name:"minecraft:generic.follow_range"}],FoodLevel:0b,Invulnerable:0b,FallFlying:0b,ForcedAge:0,Gossips:[],PortalCooldown:0,AbsorptionAmount:0.0f,LastRestock:0L,FallDistance:0.0f,CanUpdate:1b,DeathTime:0s,Xp:0,LastGossipDecay:10051081L,HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,UUID:[I;-419266458,1089883251,-1176043008,1186277360],Age:0,Motion:[2.3489080142694366E-5d,-0.0784000015258789d,0.13487918769177593d],Health:20.0f,LeftHanded:0b,Air:300s,OnGround:1b,Rotation:[359.97888f,0.0f],HandItems:[{},{}],RestocksToday:0,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Pos:[-216.50016719842122d,64.0d,-2511.8820199442885d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:1b,VillagerData:{profession:"minecraft:none",level:1,type:"minecraft:savanna"},HurtTime:0s,Inventory:[]}]
	at me.jellysquid.mods.lithium.common.entity.tracker.EntityTrackerEngine.removeListener(EntityTrackerEngine.java:125) ~[sodium:2.0] {re:mixin,re:classloading}
	at me.jellysquid.mods.lithium.common.entity.tracker.EntityTrackerEngine.onEntityRemoved(EntityTrackerEngine.java:49) ~[sodium:2.0] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.Chunk.handler$zzp000$onEntityRemoved(Chunk.java:1423) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.Chunk.func_76608_a(Chunk.java:351) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217464_b(ServerWorld.java:663) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_174829_m(Entity.java:818) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:538) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.WorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:sodium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
```

Details:
```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at me.jellysquid.mods.lithium.common.entity.tracker.EntityTrackerEngine.removeListener(EntityTrackerEngine.java:125) ~[sodium:2.0] {re:mixin,re:classloading}
	at me.jellysquid.mods.lithium.common.entity.tracker.EntityTrackerEngine.onEntityRemoved(EntityTrackerEngine.java:49) ~[sodium:2.0] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.Chunk.handler$zzp000$onEntityRemoved(Chunk.java:1423) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.chunk.Chunk.func_76608_a(Chunk.java:351) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217464_b(ServerWorld.java:663) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_174829_m(Entity.java:818) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:538) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.entity.merchant.villager.VillagerEntity)
	Entity ID: 226
	Entity Name: Villager
	Entity's Exact location: -216.50, 64.00, -2511.88
	Entity's Block location: World: (-217,64,-2512), Chunk: (at 7,4,0 in -14,-157; contains blocks -224,0,-2512 to -209,255,-2497), Region: (-1,-5; contains chunks -32,-160 to -1,-129, blocks -512,0,-2560 to -1,255,-2049)
	Entity's Momentum: 0.00, -0.08, 0.13
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.WorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:sodium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

Thank you for looking at this issue. Also thanks for the port.

Cheers.

**Comment by yatsukiko** [comment]
do you have any other mods loaded?

**Comment by rakostep** [comment]
Hi again, here's the list on the mods installed on the server with their specific versions:

```
sodium-forge-2.0.jar
KemonoCraft-1.16.4-0.3.16
mgui-1.16.4-3.1.3
Morpheus-1.16.4-4.2.68
SereneSeasons-1.16.5-4.0.1.91-universal
TerraForged-1.16.4-0.2.7
tetra-1.16.4-3.6.1
YungsApi-1.16.4-Forge-4
AI-Improvements-1.16.2-0.3.0
smoothboot-forge-1.16.4-1.2.0
ferritecore-1.1.1
dynviewdist-1.8
MixinBootstrap-1.0.5
quickhomes-1.16.3-1.2.6
jei-1.16.4-7.6.1.71
create-mc1.16.3_v0.3e
GravityWorld+3.54+1.16.4
corpse-1.16.5-1.0.0
wooltweaks_1.16.5-1.0
unearthed-1.1.0
sisser-1.7
antiqueatlas-5.4.4-forge
BetterCaves-Forge-1.16.4-1.1.1
Clumps-6.0.0.17
collective-1.16.5-1.66
CustomSkinLoader_Forge-14.13-SNAPSHOT-214
guardvillagers-1.16.4-1.1.10
```

**Comment by yatsukiko** [comment]
duplicate of #20, in your case its "guardvillagers" mod tho, can't fix the issue but can provide a [build with that feature disabled](https://yatsukiko.me/u/sodium-forge-nne%202.1.jar)
