### ISSUE TITLE
Nether portal issue

### ISSUE THREAD

**Issue by rakostep** [Pannoniae/sodium-forge#26]
### Expected Behavior
Going to the nether with portal.

### Actual Behavior
Players get disconnected during the transfer.

### Reproduction Steps
1. Have sodium-forge-nne 2.1 on multiplayer server. 
2. Mod is on server side only. 
3. Build a nether portal, then enter.

### Attachments
N/A

### System Information
Unfortunately there's no crash reports for it however I got some excerpt of the log in the server's console:
```
22.02 04:44:00 [Server] Server thread/WARN [minecraft/NetworkSystem]: Failed to handle packet for /101.100.130.201:47419
22.02 04:44:00 [Server] INFO net.minecraft.crash.ReportedException: Ticking player
22.02 04:44:00 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
22.02 04:44:00 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading,pl:accesstransformer:B}
22.02 04:44:00 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
22.02 04:44:00 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}
22.02 04:44:00 [Server] INFO Caused by: java.lang.ClassCastException: net.minecraft.village.PointOfInterestManager cannot be cast to me.jellysquid.mods.lithium.common.world.interests.PointOfInterestDataExtended
22.02 04:44:00 [Server] INFO at net.minecraft.world.Teleporter.func_242957_a(Teleporter.java:539) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:ai.poi.fast_portals.PortalForcerMixin,pl:mixin:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.Entity.func_241830_a(Entity.java:2214) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_241830_a(ServerPlayerEntity.java:701) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.Entity.func_241829_a(Entity.java:2179) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_241829_a(ServerPlayerEntity.java:612) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
22.02 04:44:00 [Server] INFO at net.minecraftforge.common.util.ITeleporter.getPortalInfo(ITeleporter.java:84) ~[forge:?] {re:classloading,re:mixin}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntity.java:645) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.Entity.func_241206_a_(Entity.java:2120) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.Entity.func_213284_aV(Entity.java:1779) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.Entity.func_70030_z(Entity.java:403) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:295) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.Entity.func_70071_h_(Entity.java:387) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinEntity,pl:mixin:APP:sodium.mixins.json:entity.collisions.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.fast_suffocation_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:sodium.mixins.json:entity.stream_entity_collisions_lazily.EntityMixin,pl:mixin:APP:antiqueatlas.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2113) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:sodium.mixins.json:entity.block_cache.LivingEntityMixin,pl:mixin:APP:sodium.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
22.02 04:44:00 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
22.02 04:44:00 [Server] INFO ... 9 more
22.02 04:44:01 [Disconnect] User [minecraft/ServerPlayNetHandler]: RakoStep has disconnected, reason: Internal server error
22.02 04:44:01 [Server] Server thread/INFO [minecraft/DedicatedServer]: RakoStep left the game
```

I assume that the mod is the cause and  tested the server again after removing it. When I enter the portal, I can get in, so it seems this mod is having some issue on it.

**Comment by ProfessionaFiddler** [comment]
I guess the nether problem will be solved in the next release, there is a problem with points of interest

**Comment by fredderf121** [comment]
I've just discovered this fork, and I have the same problem when entering the nether (the village point of interest error). How long is a 'next release'? So far, I'm loving the port and huge kudos to the people behind this. I obviously don't have any right to feel entitled to a quicker release; I just want a estimate to temper my expectations.

**Comment by ProfessionaFiddler** [comment]
Download sodium 1.1, it has no issue with the portal.

however I have to report that stained glass will not be stained at all.

**Comment by rakostep** [comment]
Hi, sorry for the bother. I'd like to ask where is that specific version located on the releases? I can only find 1.0 and 2.0

**Comment by ProfessionaFiddler** [comment]
Looks like he is not often here, I'll try to repost that link, hold on

**Comment by ProfessionaFiddler** [comment]
https://yatsukiko.me/u/sodium-forge-1.1.jar

**Comment by rakostep** [comment]
thank you very much

**Comment by LapunEuler** [comment]
I have the same issue with nether portals on version 2.1 and 2.0, on creative and survival singleplayer worlds. The only way to move between dimension is tp command. On version 1.1 i have stable, nice FPS and tps on 30 chunk render.

I use 1.16.5 forge 36.0.58, java 14.0.2 64 bit with cutom jvm arguments, additional mods are ambient sounds, damage tilt, dynamic surroundings and no other performance mods like optifine. 

Also want to say well done job with this mod, performance is greatly improved on 1.1.

**Comment by fieldchar** [comment]
does anyone know what is yatsukiko's discord or anyway to contact him?

**Comment by fieldchar** [comment]
> https://yatsukiko.me/u/sodium-forge-1.1.jar

hey by the way where did you find this

**Comment by ProfessionaFiddler** [comment]
> > https://yatsukiko.me/u/sodium-forge-1.1.jar
> 
> hey by the way where did you find this

check closed issues about portals, he gave the link there himself
